#!/bin/sh /etc/rc.common
START=99
start() {
    echo "Starting modem initialization..."
    echo 1 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio1/direction
    echo 1 > /sys/class/gpio/gpio1/value
}
