#!/bin/sh
uci set network.lan.ipaddr='192.168.2.1'
uci set network.lan.proto='static'
uci commit network

uci set modemmanager.apn='internet'
uci set modemmanager.device='/dev/cdc-wdm0'
uci commit modemmanager
